# Ubuntu 최신 버전 이미지를 기반으로 시작
FROM ubuntu:latest

# 작업 디렉토리 설정 (컨테이너 내에서 작업할 디렉토리)
WORKDIR /app

# 패키지 목록 업데이트 및 필요한 패키지 설치
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    curl \
    vim \
    git

# 예시로, 추가적으로 설치할 Python 라이브러리 목록이 있다면 requirements.txt를 복사해서 설치하기
# COPY requirements.txt /app/requirements.txt
# RUN pip3 install -r requirements.txt

# 컨테이너 실행 시 기본적으로 실행될 명령어 설정 (터미널로 bash 실행)
CMD ["bash"]
